name: Waka Readme

on:
  # for manual workflow trigger
  workflow_dispatch:
  schedule:
    # runs at 12 AM UTC (5:30 AM IST)
    - cron: "0 0 * * *"

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: krishsavaliya7/waka-readme@main # this action name
        with:
          WAKATIME_API_KEY: ${{ secrets.waka_e5a5db8f-7375-41e1-8874-c5fd164ddf41}}
